import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type AccentColor = 'purple' | 'blue' | 'green' | 'orange' | 'red' | 'pink';
export type HeroColor = 'purple' | 'blue' | 'green' | 'orange' | 'red' | 'pink' | 'gradient';
export type Language = 'fr' | 'en';
export type Units = 'metric' | 'imperial';

export interface UserPreferences {
  accentColor: AccentColor;
  heroColor: HeroColor;
  language: Language;
  units: Units;
}

const defaultPreferences: UserPreferences = {
  accentColor: 'purple',
  heroColor: 'purple',
  language: 'fr',
  units: 'metric',
};

interface PreferencesContextValue {
  preferences: UserPreferences;
  updatePreference: <K extends keyof UserPreferences>(key: K, value: UserPreferences[K]) => Promise<void>;
  isLoading: boolean;
}

const PreferencesContext = createContext<PreferencesContextValue | undefined>(undefined);

const STORAGE_KEY = 'user_preferences';

export const PreferencesProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [preferences, setPreferences] = useState<UserPreferences>(defaultPreferences);
  const [isLoading, setIsLoading] = useState(true);

  // Charger les préférences au démarrage
  useEffect(() => {
    loadPreferences();
  }, []);

  const loadPreferences = async () => {
    try {
      const stored = await AsyncStorage.getItem(STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        setPreferences({ ...defaultPreferences, ...parsed });
      }
    } catch (error) {
      console.warn('Failed to load preferences:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const updatePreference = async <K extends keyof UserPreferences>(
    key: K,
    value: UserPreferences[K]
  ) => {
    try {
      const newPreferences = { ...preferences, [key]: value };
      setPreferences(newPreferences);
      await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(newPreferences));
    } catch (error) {
      console.warn('Failed to save preference:', error);
    }
  };

  return (
    <PreferencesContext.Provider value={{ preferences, updatePreference, isLoading }}>
      {children}
    </PreferencesContext.Provider>
  );
};

export const usePreferences = () => {
  const context = useContext(PreferencesContext);
  if (!context) {
    throw new Error('usePreferences must be used within PreferencesProvider');
  }
  return context;
};

// Couleurs d'accent disponibles
export const accentColors = {
  purple: { light: '#6366F1', dark: '#818CF8', name: 'Violet' },
  blue: { light: '#3B82F6', dark: '#60A5FA', name: 'Bleu' },
  green: { light: '#10B981', dark: '#34D399', name: 'Vert' },
  orange: { light: '#F97316', dark: '#FB923C', name: 'Orange' },
  red: { light: '#EF4444', dark: '#F87171', name: 'Rouge' },
  pink: { light: '#EC4899', dark: '#F472B6', name: 'Rose' },
};

// Couleurs pour le HeroSection
export const heroColors = {
  purple: { light: ['#6366f1', '#8b5cf6'], dark: ['#1e1b4b', '#312e81'], name: 'Violet' },
  blue: { light: ['#3b82f6', '#1d4ed8'], dark: ['#1e3a8a', '#1e40af'], name: 'Bleu' },
  green: { light: ['#10b981', '#059669'], dark: ['#064e3b', '#065f46'], name: 'Vert' },
  orange: { light: ['#f97316', '#ea580c'], dark: ['#9a3412', '#c2410c'], name: 'Orange' },
  red: { light: ['#ef4444', '#dc2626'], dark: ['#7f1d1d', '#991b1b'], name: 'Rouge' },
  pink: { light: ['#ec4899', '#db2777'], dark: ['#831843', '#9d174d'], name: 'Rose' },
  gradient: { light: ['#6366f1', '#8b5cf6', '#a855f7'], dark: ['#1e1b4b', '#312e81', '#4c1d95'], name: 'Dégradé' },
};

// Textes de langue
export const translations = {
  fr: {
    // Navigation
    home: 'Accueil',
    explore: 'Explorer',
    feed: 'Feed',
    messages: 'Messages',
    profile: 'Profil',
    menu: 'Menu',
    
    // Stats et données
    lastWorkout: 'Dernière séance',
    thisWeek: 'Cette semaine',
    sessions: 'séances',
    completed: 'terminées',
    streak: 'Streak',
    today: 'Aujourd\'hui',
    yesterday: 'Hier',
    daysAgo: 'Il y a {days}j',
    getBackToIt: 'Reprends !',
    itsBeenAWhile: 'Ça fait un moment...',
    goalReached: 'Objectif atteint ! 🎯',
    newRecord: 'Nouveau record ! 🔥',
    personalRecord: 'Record personnel',
    progression: 'Progression',
    level: 'Niveau',
    
    // Sections principales
    quickActions: 'Actions rapides',
    myWorkouts: 'Mes séances',
    lastCreatedWorkout: 'Dernière séance créée',
    draftInProgress: 'Brouillon en cours',
    lastCompletedWorkout: 'Dernière séance terminée',
    completedSession: 'Séance complétée',
    
    // États vides
    noWorkoutInProgress: 'Aucune séance en cours',
    createFirstWorkout: 'Crée ta première séance pour commencer',
    noCompletedWorkout: 'Aucune séance terminée',
    completeWorkoutToSee: 'Termine une séance pour la voir apparaître ici',

    // Welcome empty state
    welcome: 'Bienvenue',
    welcomeEmpty: "C'est le moment de commencer ton parcours fitness. Crée ta première séance pour suivre tes progrès !",
    createMyFirstWorkout: 'Créer ma première séance',
    discoverPrograms: 'Découvrir les programmes',
    tipCreateTitle: 'Crée',
    tipCreateDesc: 'Compose ta séance avec tes exercices',
    tipTrackTitle: 'Progresse',
    tipTrackDesc: 'Suis tes stats et bats tes records',

    // Actions
    createWorkout: 'Créer une séance',
    newWorkout: 'Nouvelle séance',
    newProgram: 'Nouveau programme',
    drafts: 'Brouillons',
    seeAll: 'Voir les',
    defaultWorkoutTitle: 'Séance',
    feedWorkoutTitle: 'Séance du feed',
    workoutCopy: '{title} (copie)',
    workoutCopyN: '{title} (copie {n})',
    errorWorkoutNotFound: 'Séance introuvable',
    errorProfileUnavailable: 'Profil utilisateur indisponible',
    errorWorkoutNotSynced: 'Séance pas encore synchronisée. Attends quelques secondes et réessaie.',
    errorFeedLoad: 'Impossible de charger le feed',
    
    // Settings
    settings: 'Paramètres',
    appearance: 'Apparence',
    languageAndRegion: 'Langue et région',
    preferences: 'Préférences',
    language: 'Langue',
    units: 'Unités',
    unitSystem: 'Système d\'unités',
    accentColor: 'Couleur d\'accent',
    heroColor: 'Couleur de l\'en-tête',
    darkMode: 'Mode sombre',
    darkModeDescription: 'Interface sombre pour tes yeux',
    french: 'Français',
    english: 'English',
    metric: 'Métrique',
    imperial: 'Impérial',
    
    // Informations
    basicInfo: 'Informations de base',
    personalInfo: 'Informations personnelles',
    fitnessGoals: 'Objectifs fitness',
    username: 'Nom d\'utilisateur',
    bio: 'Bio',
    mainGoal: 'Objectif principal',
    location: 'Localisation',
    height: 'Taille',
    weight: 'Poids',
    
    // Navigation drawer
    history: 'Historique',
    objectives: 'Objectifs',
    parameters: 'Paramètres',
    
    // Unités
    kg: 'kg',
    lbs: 'lbs',
    cm: 'cm',
    ft: 'ft',
    
    // Messages d'état
    loading: 'Chargement...',
    loadingSettings: 'Chargement des paramètres...',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    error: 'Erreur',
    
    // Greetings and motivational messages
    goodMorning: 'Bonjour',
    goodAfternoon: 'Bon après-midi',
    goodEvening: 'Bonsoir',
    consecutiveDays: 'jours consécutifs',
    daysInARow: 'jours de suite',
    readyForWorkout: 'Prêt pour ta séance ?',
    letsGo: 'C\'est parti !',
    
    // Experience levels
    beginner: 'Débutant',
    beginnerDesc: 'Moins de 6 mois',
    intermediate: 'Intermédiaire',
    intermediateDesc: '6 mois - 2 ans',
    advanced: 'Avancé',
    advancedDesc: 'Plus de 2 ans',
    
    // Objectives
    muscleGain: 'Prise de masse',
    weightLoss: 'Perte de poids',
    strength: 'Force',
    endurance: 'Endurance',
    generalFitness: 'Forme générale',
    sportSpecific: 'Sport spécifique',
    
    // Equipment
    dumbbells: 'Haltères',
    barbell: 'Barre olympique',
    machines: 'Machines',
    kettlebells: 'Kettlebells',
    bands: 'Élastiques',
    bodyweight: 'Poids du corps',
    trx: 'TRX',
    bench: 'Banc',
    squat_rack: 'Rack à squat',
    cardio: 'Cardio (tapis, vélo...)',
    
    // Gender
    male: 'Homme',
    female: 'Femme',
    other: 'Autre',
    preferNotToSay: 'Préfère ne pas dire',
    
    // Form labels and descriptions
    yourUsername: 'Ton pseudo',
    tellAboutYou: 'Parle de toi...',
    locationPlaceholder: 'Paris, France',
    heightCm: 'Taille (cm)',
    weightKg: 'Poids (kg)',
    heightPlaceholder: '175',
    weightPlaceholder: '70',
    gender: 'Genre',
    experienceLevel: 'Niveau d\'expérience',
    trainingFrequency: 'Fréquence d\'entraînement (fois par semaine)',
    availableEquipment: 'Équipement disponible',
    publicShare: 'Partage public',
    publicShareDesc: 'Autoriser le partage de tes séances publiquement',
    saveCompleteProfile: 'Sauvegarder le profil complet',
    guideTitle: 'Guide d\'utilisation',
    guideUsage: 'Voir le guide et les explications',
    demoButton: 'Lancer la démo (30 s)',
    actions: 'Actions',
    logout: 'Se déconnecter',
    logoutConfirm: 'Es-tu sûr de vouloir te déconnecter ?',
    logoutButton: 'Déconnexion',
    version: 'Gorillax v1.0.0',
    
    // Error messages
    usernameRequired: 'Le nom d\'utilisateur ne peut pas être vide',
    usernameTaken: 'Ce nom d\'utilisateur est déjà pris',
    cannotSaveInfo: 'Impossible de sauvegarder les informations',
    cannotSaveProfile: 'Impossible de sauvegarder le profil complet',
    profileSaved: '✅ Informations mises à jour !',
    profileCompleteSaved: '✅ Profil complet sauvegardé !',
    goalError: 'L\'objectif doit être entre 1 et 14 séances par semaine.',
    cannotSaveGoal: 'Impossible de sauvegarder l\'objectif.',
    weeklyGoal: 'Objectif hebdomadaire',
    howManySessionsPerWeek: 'Combien de séances veux-tu faire par semaine ?',

    // General UI
    defaultUser: 'Utilisateur',
    untitled: 'Sans titre',
    delete: 'Supprimer',
    info: 'Info',
    total: 'Total',

    // Profile
    noBioDefined: 'Aucune bio définie',
    editProfile: 'Modifier le profil',
    profileUpdated: '✅ Profil mis à jour !',
    avatarUploadComingSoon: "Fonctionnalité d'upload d'avatar à venir !",
    photoPermissionDesc: "Autorise l'accès à tes photos pour changer ton avatar.",
    permissionRequired: 'Permission requise',
    objectiveLabel: 'Objectif',
    objectivePlaceholder: 'Ex: Prise de masse, Perte de poids...',
    sessionsLabel: 'Séances',
    exercisesLabel: 'Exercices',
    setsLabel: 'séries',

    // Navigation/Menu items
    myPublicProfile: 'Mon profil public',
    memberCard: 'Carte membre / Pass Salle',
    myProgram: 'Mon Programme',
    myObjectives: 'Mes Objectifs',
    notifications: 'Notifications',
    termsOfUse: "Conditions d'utilisation",
    privacyLabel: 'Confidentialité',
    settingsSection: 'Réglages',
    createProgram: 'Créer un programme',
    progressionNav: 'Progression',

    // QuickStats explanations
    objectiveExplanation: 'Nombre de séances terminées cette semaine par rapport à ton objectif de {goal} séances par semaine.',
    volumeKg: 'Volume (kg)',
    volumeExplanation: 'Volume total soulevé cette semaine (poids × répétitions). Compare avec la semaine précédente.',
    streakExplanation: 'Nombre de jours consécutifs avec au moins une séance terminée. Continue pour maintenir ta série !',
    draftsExplanation: 'Séances en cours de création ou en attente.',
    completedLabel: 'Terminées',
    completedExplanation: 'Séances complètement terminées et enregistrées.',

    // Milestones
    sessionsCount: '{count} séances',
    daysInARowCount: '{count} jours de suite',
    volumeThisWeek: 'Volume cette semaine',
    startWorkout: 'Commencer une séance',
    sessionsPerMonth: 'Séances par mois',

    // Pass / Wallet
    passDescription: "Présentez ce pass à l'entrée ou sur la machine en salle partenaire Gorillax.",
    loginRequired: 'Connexion requise',
    loginToAddPass: 'Connecte-toi pour ajouter le pass.',
    addToAppleWallet: 'Ajouter à Apple Wallet',
    addToGoogleWallet: 'Ajouter à Google Wallet',
    googleWalletLink: 'Lien Google Wallet',
    memberCardTitle: 'Carte membre',
    gorillaxMemberCard: 'Carte membre Gorillax',
    cannotOpenPass: "Impossible d'ouvrir le pass. Vérifie ta connexion.",
    notConfigured: 'Non configuré',
    googleWalletNotConfigured: "Google Wallet n'est pas encore configuré sur ce serveur.",
    cannotOpenGoogleWallet: "Impossible d'ouvrir Google Wallet. Vérifie ta connexion.",
    openLink: 'Ouvre le lien',
    openInSafari: 'Ouvre ce lien dans Safari pour ajouter le pass.',

    // Messages
    workoutLabelSingle: 'Séance',
    viewWorkout: 'Voir la séance',
    onlineStatus: 'En ligne',
    startConversation: 'Commencez la conversation',
    sendFirstMessageTo: 'Envoyez votre premier message à {name}',
    writeMessage: 'Écrivez un message...',

    // Share post
    newPost: 'Nouveau post',
    publish: 'Publier',
    previewLabel: 'Aperçu',
    myWorkout: 'Ma séance',
    descriptionLabel: 'Description',
    describeWorkout: 'Raconte ta séance, tes ressentis, tes progrès...',
    colorLabel: 'Couleur',
    photoLabel: 'Photo',
    changePhoto: 'Changer la photo',
    addPhoto: 'Ajouter une photo',
    tapToReplace: 'Appuie pour remplacer',
    fromGallery: 'Depuis ta galerie',
    photoPermissionMessage: "Autorise l'accès à ta galerie pour ajouter une photo.",
    cannotPublish: 'Impossible de publier.',

    // Leaderboard
    rankings: 'Classements',
    followersLabel: 'Abonnés',
    sevenDays: '7 jours',
    thirtyDays: '30 jours',
    allTime: 'Tout',
    youLabel: 'Toi',
    placeLabel: 'place',
    placesLabel: 'places',
    yourRankIs: 'Tu es #{rank} au classement !',
    rankingSection: 'CLASSEMENT',
    noRankingYet: 'Pas encore de classement',
    shareToAppear: 'Partage tes séances pour apparaître ici !',
    challengesTab: 'Défis',
    activeChallenges: 'Défis actifs',
    moreChallengesSoon: 'Plus de défis bientôt',
    moreChallengesSoonDesc: 'De nouveaux défis seront ajoutés régulièrement. Reste connecté !',
    leaderVolume: 'Volume',
    leaderSessions: 'Séances',
    leaderLikes: 'Likes',
    leaderFollowers: 'Abonnés',

    // Notifications
    justNow: "À l'instant",
    commentLabel: 'Commentaire',
    subscriptionLabel: 'Abonnement',
    mentionLabel: 'Mention',
    notificationLabel: 'Notification',
    olderLabel: 'Plus ancien',
    someone: "Quelqu'un",
    noNotifications: 'Pas de notifications',
    notificationEmptyDesc: "Tu recevras des notifications quand quelqu'un interagit avec tes séances",
    exploreFeed: 'Explorer le feed',
    likesLabel: 'Likes',
    commentsLabel: 'Commentaires',
    deleteAction: 'Supprimer',
    markAsRead: 'Marquer comme lu',
    notificationActions: 'Actions',
    clearAllNotifications: 'Tout supprimer',
    clearAllNotificationsDesc: 'Supprimer toutes les notifications ? Cette action est irréversible.',
    clearAll: 'Tout supprimer',
    allFilter: 'Tout',
    followsFilter: 'Abonnements',
    noNotificationsForFilter: 'Aucune notification de ce type',
    notificationFilterEmptyDesc: "Tu n'as pas encore reçu ce type de notification.",
    showAllNotifications: 'Voir toutes les notifications',

    // Library
    thisMonth: 'Ce mois-ci',
    deleteWorkoutTitle: 'Supprimer la séance',
    confirmDeleteWorkout: 'Veux-tu vraiment supprimer "{title}" ?',
    minutesAgo: 'il y a {n}min',
    hoursAgo: 'il y a {n}h',
    doneLabel: 'Terminé',
    inProgressLabel: 'En cours',
    setsProgress: '{completed}/{total} séries',
    completedStatus: 'Complété',
    viewLabel: 'Consulter',
    startLabel: 'Démarrer',
    myLibrary: 'Ma Bibliothèque',
    totalWorkoutsCount: '{count} séances au total',
    searchWorkout: 'Rechercher une séance...',
    newSession: 'Nouvelle séance',

    // Explore
    searchPlaceholder: 'Rechercher...',
    allCategory: 'Tout',
    forceCategory: 'Force',
    cardioCategory: 'Cardio',
    massCategory: 'Masse',
    lossCategory: 'Perte',
    trendingSection: 'Tendances',
    suggestedSection: 'Suggérés',
    challengesSection: 'Défis',
    follow: 'Suivre',
    following: 'Suivi',

    // Programme
    generateProgram: 'Générer un programme',
    programObjective: 'Objectif du programme',
    frequency: 'Fréquence',
    timesPerWeek: 'fois par semaine',
    exercisesPerSession: 'Exercices par séance',
    duration: 'Durée',
    weeks: 'semaines',
    hypertrophy: 'Hypertrophie',
    cutting: 'Sèche',
    forceLabel: 'Force',
    recomposition: 'Recomposition',
    wellBeing: 'Bien-être',
    myPrograms: 'Mes programmes',
    noPrograms: 'Aucun programme',
    createFirstProgram: 'Crée ton premier programme personnalisé',
    programSaved: 'Programme sauvegardé !',
    cannotGenerateProgram: 'Impossible de générer le programme.',
    cannotSaveProgram: 'Impossible de sauvegarder le programme.',
    importToWorkouts: 'Importer dans mes séances',
    saveProgram: 'Sauvegarder le programme',
    programImported: 'Programme importé dans tes séances !',

    // Register
    createAccount: 'Créer un compte',
    usernamePlaceholder: "Nom d'utilisateur",
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Mot de passe',
    confirmPasswordPlaceholder: 'Confirmer le mot de passe',
    alreadyHaveAccount: 'Déjà un compte ?',
    loginLink: 'Se connecter',
    registerButton: "S'inscrire",
    createYourAccount: 'Crée ton compte',
    usernameLabel: "Nom d'utilisateur",
    chooseUsername: "Choisis un nom d'utilisateur",
    emailLabel: 'Email',
    emailExample: 'ton@email.com',
    passwordLabel: 'Mot de passe',
    passwordMinChars: 'Au moins 8 caractères',
    confirmPasswordLabel: 'Confirmer le mot de passe',
    repeatPassword: 'Répète ton mot de passe',
    fillAllFields: 'Veuillez remplir tous les champs',
    usernameMinLength: "Le nom d'utilisateur doit contenir au moins 3 caractères",
    invalidEmail: 'Veuillez entrer une adresse email valide',
    passwordMinLength: 'Le mot de passe doit contenir au moins 8 caractères',
    passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
    registrationError: "Erreur lors de l'inscription",

    // Explore extra
    exploreTitle: 'Explorer',
    discoverWorkouts: 'Découvre des séances inspirantes',
    searchWorkoutsUsers: 'Rechercher des séances, utilisateurs...',
    participate: 'Participer',
    usersSection: 'Utilisateurs',
    workoutsSection: 'Séances',
    noResults: 'Aucun résultat',
    noResultsFor: 'Aucun résultat pour',
    searchInProgress: 'Recherche en cours...',
    toDiscover: 'À découvrir',
    seeAllLabel: 'Voir tout',
    challengesOfMoment: 'Défis du moment',
    nothingToExplore: 'Rien à explorer pour le moment',
    communityWorkoutsWillAppear: 'Les séances partagées par la communauté apparaîtront ici',
    createSession: 'Créer une séance',
    noSessionFound: 'Aucune séance trouvée',
    noSessionForCategory: 'Aucune séance',
    forTheMoment: 'pour le moment',
    seeEverything: 'Voir tout',
    loadingText: 'Chargement...',
    subscriberCount: 'abonné',
    subscribersCount: 'abonnés',
    exosCount: 'exos',

    // Objectives extra
    sessionsPerWeekTitle: 'Séances par semaine',
    sessionsPerWeekDesc: 'Nombre de séances à réaliser chaque semaine',
    weeklyVolumeTitle: 'Volume hebdomadaire',
    weeklyVolumeDesc: 'Poids total soulevé par semaine',
    sessionsPerMonthTitle: 'Séances par mois',
    sessionsPerMonthDesc: 'Objectif mensuel de séances',
    dayStreakTitle: 'Série de jours',
    dayStreakDesc: 'Nombre de jours consécutifs avec une séance',
    squatRecordTitle: 'Record Squat',
    squatRecordDesc: 'Poids maximum au squat',
    benchRecordTitle: 'Record Développé couché',
    benchRecordDesc: 'Poids maximum au développé couché',
    sessionsUnit: 'séances',
    daysUnit: 'jours',
    cannotSaveObjectives: 'Impossible de sauvegarder les objectifs.',
    enterValidValue: 'Veuillez entrer une valeur valide.',
    fillRequiredFields: 'Veuillez remplir tous les champs obligatoires.',
    enterValidTarget: 'Veuillez entrer une valeur cible valide.',
    deleteObjectiveTitle: "Supprimer l'objectif",
    deleteObjectiveConfirm: 'Veux-tu vraiment supprimer "{title}" ?',
    deleteLabel: 'Supprimer',
    cancelLabel: 'Annuler',
    editObjectiveTitle: "Modifier l'objectif",
    goalInUnit: 'Objectif en {unit}',
    saveLabel: 'Enregistrer',
    newObjectiveTitle: 'Nouvel objectif',
    titleRequired: 'Titre *',
    titlePlaceholder: 'Ex: Record Deadlift',
    objectiveDescriptionPlaceholder: "Description de l'objectif",
    targetRequired: 'Objectif *',
    unitLabel: 'Unité',
    colorLabelObj: 'Couleur',
    createLabel: 'Créer',
    defineGoalsAndTrack: 'Définissez vos objectifs et suivez votre progression',

    // Programme create extra
    createProgramTitle: 'Créer un programme',
    customizeTraining: 'Personnalise ton entraînement selon tes objectifs',
    objectiveSection: 'Objectif',
    hypertrophyLabel: 'Hypertrophie',
    forceOptionLabel: 'Force',
    enduranceLabel: 'Endurance',
    fitnessLabel: 'Fitness',
    massGainDesc: 'Prise de masse',
    maxPowerDesc: 'Puissance max',
    muscularCardioDesc: 'Cardio musculaire',
    fitnessDesc: 'Remise en forme',
    suggestionsBasedOnProfile: 'Suggestions basées sur ton profil',
    smartPersonalization: 'Personnalisation intelligente',
    suggestedObjective: 'Objectif suggéré:',
    suggestedLevel: 'Niveau suggéré:',
    suggestedFrequency: 'Fréquence suggérée:',
    applyLabel: 'Appliquer',
    suggestionsNote: 'Ces suggestions sont basées sur les informations de ton profil',
    parametersSection: 'Paramètres',
    frequencyLabel: 'Fréquence',
    perSessionLabel: 'Par séance',
    durationLabel: 'Durée',
    sessionLabel: 'Séance',
    levelSection: 'Niveau',
    beginnerLevel: 'Débutant',
    intermediateLevel: 'Intermédiaire',
    advancedLevel: 'Avancé',
    methodSection: 'Méthode',
    autoMethod: 'Auto',
    optimalChoice: 'Choix optimal',
    fullBody: 'Full Body',
    wholeBody: 'Corps entier',
    upperLower: 'Upper/Lower',
    upperLowerDesc: 'Haut/Bas',
    pplMethod: 'PPL',
    pplDesc: 'Push/Pull/Legs',
    equipmentSection: 'Équipement',
    selectedCount: 'sélectionné',
    selectedPluralCount: 'sélectionnés',
    barreLabel: 'Barre',
    dumbbellsLabel: 'Haltères',
    bodyweightLabel: 'Poids du corps',
    machinesLabel: 'Machines',
    cablesLabel: 'Câbles',
    kettlebellLabel: 'Kettlebell',
    constraintsSection: 'Contraintes',
    constraintsPlaceholder: 'Ex: Genou fragile, dos sensible...',
    howItWorksTitle: 'Comment ça marche ?',
    howItWorksSubtitle: 'Notre algorithme crée ton programme selon la science du sport',
    howItWorks1Title: 'Volume adapté',
    howItWorks1Desc: 'Le nombre de séries par muscle est calculé selon ton niveau, en suivant les recommandations scientifiques (10-20 séries/semaine par muscle).',
    howItWorks2Title: 'Composés en priorité',
    howItWorks2Desc: 'Chaque séance commence par les exercices polyarticulaires (squat, développé, rowing...) puis les isolations. C\'est la méthode la plus efficace.',
    howItWorks3Title: 'Progression intégrée',
    howItWorks3Desc: 'Le volume et l\'intensité augmentent semaine après semaine. Si ton programme fait 5+ semaines, une semaine de deload est ajoutée automatiquement.',
    howItWorks4Title: 'Reps intelligentes',
    howItWorks4Desc: 'Les composés utilisent des plages de reps lourdes (6-8), les accessoires modérées (8-12), et les isolations légères (12-15). Adapté à ton objectif.',
    frequencyHelper: 'Chaque muscle doit être travaillé au moins 2x/semaine. 3-4x est idéal pour la plupart.',
    durationHelper: '4 semaines = 1 mésocycle. 5+ semaines = deload automatique.',
    sessionDurationHelper: '45-60 min est optimal. Au-delà de 75 min, la performance baisse.',
    levelHelper: 'Ton niveau détermine le volume de séries et la complexité des exercices.',
    methodHelper: 'Le mode Auto choisit le split optimal selon ta fréquence.',
    generationInProgress: 'Génération en cours...',
    generateMyProgram: 'Générer mon programme',
    generationImpossible: 'Génération impossible',
    programNotFound: 'Programme introuvable',
    loginRequiredToSave: 'Tu dois être connecté pour enregistrer les séances.',
    connectionRequired: 'Connexion requise',
    sessionsRegistered: 'Séances enregistrées !',
    sessionRegisteredCount: '{count} séance enregistrée.',
    sessionsRegisteredCount: '{count} séances enregistrées.',
    cannotSave: "Impossible d'enregistrer",
    emptySession: 'Séance vide',
    sessionHasNoSets: 'Cette séance ne contient pas de séries.',
    cannotCreateSession: 'Impossible de créer la séance',
    cannotStart: 'Impossible de démarrer',
    sportMode: 'Sport',
    startSession: 'Démarrer',
    exerciseMore: 'exercice',
    exercisesMore: 'exercices',
    repsLabel: 'reps',
    rpeLabel: 'RPE',
    seeDetails: 'Voir le détail',
    hideDetails: 'Masquer',
    savingInProgress: 'Enregistrement...',
    saveAllSessions: 'Enregistrer toutes les séances',
    savedBadge: 'Sauvé',
    sessionsLabel2: 'séances',
    semLabel: 'sem',

    // Programme index extra
    myProgramsTitle: 'Mes Programmes',
    createYourFirstProgram: 'Crée ton premier programme',
    loadingPrograms: 'Chargement des programmes...',
    cannotLoadPrograms: 'Impossible de charger les programmes',
    errorTitle: 'Erreur',
    retryLabel: 'Réessayer',
    createProgramButton: 'Créer un programme',
    programsCount: 'programme',
    programsCountPlural: 'programmes',
    emptyProgramDesc: "Crée ton premier programme personnalisé pour organiser tes séances d'entraînement",
    generalLabel: 'Général',
    sessionsCountLabel: 'séances',
    emptySessionAlert: 'Séance vide',
    emptySessionAlertDesc: 'Cette séance ne contient pas de séries.',
    cannotStartSession: 'Impossible de démarrer la séance',

    // Login
    loginTitle: 'Connecte-toi à ton compte',
    yourPassword: 'Ton mot de passe',
    loginButton: 'Se connecter',
    demoLoginButton: 'Essayer avec le compte Demo',
    notRegisteredYet: 'Pas encore inscrit ? Créer un compte',
    connectionError: 'Erreur de connexion',
    demoConnectionError: 'Impossible de se connecter au compte demo',

    // Messages tab
    conversations: 'Conversations',
    unreadLabel: 'Non lus',
    noMessage: 'Aucun message',
    noConversation: 'Aucune conversation',
    startChattingDesc: "Commencez à discuter avec d'autres athlètes !",
    newConversation: 'Nouvelle conversation',
    loadDemoConversations: 'Charger des conversations démo',
    yourConversations: 'VOS CONVERSATIONS',

    // Profile basic page
    myProfileTitle: 'Mon profil',
    profilePageDesc: 'Choisis un pseudo et indique si tu acceptes de rendre tes séances partagées publiques.',
    pseudo: 'Pseudo',
    sharePublicly: 'Partager publiquement',
    sharePubliclyDesc: 'Active ce réglage pour autoriser tes séances partagées à apparaître dans le feed.',
    pseudoRequired: 'Pseudo requis',
    enterPseudo: 'Merci de saisir un pseudo.',
    profileRegistered: 'Profil enregistré',
    preferencesUpdated: 'Tes préférences ont été mises à jour.',
    savingFailed: 'Enregistrement impossible',
    retryLater: 'Réessaie plus tard.',
    loadingProfile: 'Chargement du profil…',
    accountSection: 'Compte',
    loggedInAs: 'Connecté en tant que :',
    disconnectLabel: 'Se déconnecter',
    disconnectTitle: 'Déconnexion',

    // Library extra
    daysAgoShort: 'il y a {n}j',

    // Shared workout detail
    workoutNotFound: 'Séance non trouvée',
    loadingError: 'Erreur de chargement',
    sharedWorkout: 'Séance partagée',
    back: 'Retour',
    setLabel: 'Série',
    weightHeader: 'Poids',
    repsHeader: 'Reps',
    totalVolume: 'Volume total',
    exercisesCount: '{count} exercices',
    setsCount: '{count} séries',

    // Profile [id] page
    profileNotFound: 'Profil introuvable',
    profileNotFoundDesc: "Ce profil n'existe pas ou a été supprimé",
    noBio: 'Aucune bio',
    likesReceived: "{count} J'aime reçus",
    editProfileLabel: 'Modifier le profil',
    noSharedWorkout: 'Aucune séance partagée',
    noSavedPost: 'Aucun post sauvegardé',
    sharedWorkoutsWillAppear: 'Les séances que tu partages apparaîtront ici',
    savedPostsWillAppear: 'Les posts que tu sauvegardes apparaîtront ici',
    profileNotSharedYet: "Ce profil n'a pas encore partagé de séance",
    postsTab: 'Posts',
    savedTab: 'Sauvegardés',
    subscribersLabel: 'Abonnés',
    followingCountLabel: 'Suivis',
    messageLabel: 'Message',
    followedLabel: 'Abonné',

    // Profile setup
    tellAboutYourself: 'Parlez-nous de vous',
    personalizeExperience: 'Ces informations nous aideront à personnaliser votre expérience',
    bioOptional: 'Bio (optionnel)',
    describeBriefly: 'Décrivez-vous en quelques mots...',
    locationOptional: 'Localisation (optionnel)',
    genderOptional: 'Genre (optionnel)',
    fitnessObjectives: 'Vos objectifs fitness',
    adaptedPrograms: 'Aidez-nous à créer des programmes adaptés',
    mainObjective: 'Objectif principal',
    desiredFrequency: "Fréquence d'entraînement souhaitée",
    preferencesTitle: 'Préférences',
    lastStepPersonalize: 'Dernière étape pour personnaliser votre expérience',
    consentPublicShare: "J'accepte de partager mes séances publiquement",
    canChangeSettingsLater: 'Vous pourrez modifier ce paramètre à tout moment dans les réglages',
    stepOf: 'Étape {current} sur {total}',
    saving: 'Sauvegarde...',
    finish: 'Terminer',
    next: 'Suivant',
    skipForNow: "Passer pour l'instant",
    testFinish: 'Test Terminer',

    // Feed
    feedLoading: 'Chargement du feed...',
    feedEmptyTitle: 'Ton feed est vide',
    feedEmptySubtitle: "Suis d'autres utilisateurs pour voir leurs séances et partager les tiennes !",
    loadMorePosts: 'Charger plus de posts',
    feedUpToDate: 'Tu es à jour !',
    commentsTitle: 'Commentaires',
    noCommentsYet: 'Pas encore de commentaires',
    beFirstToComment: 'Sois le premier à commenter cette séance !',
    addCommentPlaceholder: 'Ajouter un commentaire...',

    // Messages chat
    workoutFallback: 'Séance',
    sharedWorkoutLabel: 'Séance partagée',

    // Messages new
    newConversationTitle: 'Nouvelle conversation',
    searchUserPlaceholder: 'Rechercher un utilisateur...',
    searching: 'Recherche...',
    findAthlete: 'Trouvez un athlète',
    searchByUsername: "Recherchez par nom d'utilisateur pour démarrer une conversation",
    noUserFoundFor: 'Aucun utilisateur trouvé pour "{query}"',
    resultCountLabel: '{count} RÉSULTAT(S)',
    creatingConversation: 'Création...',

    // Page headers
    sessionDetail: 'Détail séance',
    sessionTracking: 'Suivi séance',

    // Leaderboard
    sessionsTabLabel: 'Séances',
    followersTabLabel: 'Abonnés',
    allTimePeriod: 'Tout',

    // Guide
    guideIntro: 'Découvre comment tirer le meilleur parti de Gorillax : suivi des séances, programmes, feed social et plus encore.',
    guideHomeTitle: 'Accueil',
    guideHomeContent: "Sur l'onglet Accueil tu vois ton tableau de bord : ton streak (jours consécutifs), l'objectif de la semaine (ex. 3/4 séances) et ta prochaine séance. Utilise le menu (icône hamburger) pour accéder à la Progression, à Mon Programme et aux Paramètres. Tu peux lancer une séance en un clic depuis la carte « Prochaine séance ».",
    guideCreateTitle: 'Créer et faire une séance',
    guideCreateContent: "Depuis l'accueil ou le menu, choisis « Créer une séance ». Donne un titre (ex. Push Day), ajoute des exercices depuis la bibliothèque (recherche par nom). Pendant l'entraînement, note tes séries : poids, reps, RPE. Le chrono entre les séries t'aide à garder le rythme. Quand tu as fini, marque la séance comme terminée : elle sera enregistrée dans ton historique et ta progression.",
    guideProgramTitle: 'Mon Programme',
    guideProgramContent: "Dans Mon Programme tu organises tes semaines : tu vois tes séances par jour. Clique sur une séance pour la lancer et la faire. Tu peux aussi créer un nouveau programme (Créer un programme) pour planifier plusieurs semaines à l'avance.",
    guideFeedTitle: 'Réseau (Feed)',
    guideFeedContent: "L'onglet Réseau affiche le feed : les séances partagées par la communauté. Tu peux liker un post (cœur), commenter, et cliquer sur un pseudo pour voir le profil public (stats, bio, séances). Le classement (volume, fréquence) est accessible depuis le feed pour te comparer aux autres.",
    guideExploreTitle: 'Explorer et défis',
    guideExploreContent: "Dans l'onglet Explorer tu découvres les défis communautaires. Ouvre un défi pour voir les règles et les récompenses, puis rejoins-le. Tu peux aussi rechercher des séances ou des utilisateurs depuis la barre de recherche.",
    guideMessagesTitle: 'Messages',
    guideMessagesContent: "L'onglet Messages liste tes conversations. Ouvre une conversation ou crée un nouveau message pour échanger en privé avec un autre membre. Tu peux aussi envoyer un message depuis le profil d'un utilisateur (bouton « Envoyer un message »).",
    guideProfileTitle: 'Profil et paramètres',
    guideProfileContent: "Sur ton Profil tu vois ton avatar, pseudo, bio, objectif et tes stats (séances, exercices). Depuis le menu du profil : Mon profil public, Progression, Mon Programme, Mes Objectifs, Notifications. Les Réglages donnent accès aux Paramètres (infos, préférences, apparence, langue), aux Conditions d'utilisation et à la Confidentialité. Le bouton Déconnexion te ramène à l'écran de connexion.",
    guideFooter: 'Bonne séance avec Gorillax',

    // Explore challenges
    challenge100Pushups: '100 pompes',
    challenge100PushupsDesc: '100 pompes en 1 jour',
    challenge7Days: 'Défi 7 jours',
    challenge7DaysDesc: '7 séances en 7 jours',
    challengePRSquad: 'PR Squad',
    challengePRSquatDesc: 'Bats ton PR squat',
    challengeCardioMaster: 'Cardio Master',
    challengeCardioMasterDesc: '30min cardio/jour',

    // WorkoutCard
    viewAction: 'Consulter',
    continueAction: 'Continuer',
    startAction: 'Démarrer',
    untitledWorkout: 'Séance sans nom',

    // Demo
    demoHomeTitle: 'Accueil',
    demoHomeDesc: 'Ton tableau de bord : streak, objectif de la semaine et prochaine séance. Le menu (☰) donne accès à la progression et aux programmes.',
    demoFeedTitle: 'Réseau (Feed)',
    demoFeedDesc: 'Les séances partagées par la communauté. Like (❤️) et commente les posts.',
    demoExploreTitle: 'Explorer',
    demoExploreDesc: 'Défis communautaires et découverte de séances. Rejoins un défi pour te mesurer aux autres.',
    demoMessagesTitle: 'Messages',
    demoMessagesDesc: 'Tes conversations privées avec les autres membres.',
    demoProfileTitle: 'Profil',
    demoProfileDesc: 'Tes stats, ton menu (Progression, Programme, Objectifs, Paramètres) et la déconnexion.',
    demoFinishTitle: "C'est parti !",
    demoFinishDesc: 'Tu as vu l\'essentiel. Crée une séance depuis le menu, suis ton programme et partage sur le feed. Bonne séance 🦍',

    // FeedCard
    reportPostTitle: '🚨 Signaler ce post',
    reportPostWhy: 'Pourquoi signales-tu ce post ?',
    inappropriateContent: 'Contenu inapproprié',
    spam: 'Spam',
    harassment: 'Harcèlement',
    reportThanksTitle: '✅ Merci',
    reportThanksMsg: 'Ton signalement a été envoyé. Nous allons examiner ce post.',
    report: 'Signaler',
    hide: 'Masquer',
    hideSeeNoMore: 'Ne plus voir ce post',
    exercises: 'exercices',
    sets: 'séries',
    saved: 'Enregistré',
    likesCount: "J'aime",
    sharedWorkoutDefault: 'a partagé sa séance 💪',
    viewCommentsCount: 'Voir les {count} commentaire{plural}',
    addComment: 'Ajouter un commentaire...',
    sendTo: 'Envoyer à...',
    noUserFound: 'Aucun utilisateur trouvé',
    retry: 'Réessayer',

    // NextWorkoutCard
    launchAction: 'Lancer',
    exercisesMinFormat: '{count} exercices • {duration} min',

    // Challenge detail
    challengeHeader: 'Défi',
    backLabel: 'Retour',
    challengeNotFound: 'Défi introuvable',
    challengeJoinedTitle: '🎉 Inscrit !',
    challengeJoinedMsg: 'Tu participes maintenant au défi "{title}". Bonne chance !',
    challengeJoinedBtn: "C'est parti !",
    challengeLeaveTitle: 'Quitter le défi ?',
    challengeLeaveMsg: 'Tu perdras ta progression si tu quittes maintenant.',
    challengeLeaveBtn: 'Quitter',
    difficultyEasy: 'Facile',
    difficultyMedium: 'Moyen',
    difficultyHard: 'Difficile',
    participantsLabel: 'participants',
    rulesLabel: 'Règles',
    rewardsLabel: 'Récompenses',
    challengeParticipating: 'Tu participes à ce défi',
    challengeLeave: 'Quitter le défi',
    challengeJoin: 'Rejoindre le défi',

    // History screens
    statusCompleted: 'Terminée',
    statusDraft: 'Brouillon',
    setValidated: 'Validée',
    setPlanned: 'Planifiée',
    validatedOn: 'Validée le {date}',
    exerciseLabel: 'exercice',
    serieLabel: 'série',
    seriesLabel: 'séries',
    validatedSets: 'Séries validées',
    estimatedDuration: 'Durée estimée',
    notAvailable: 'Non disponible',
    synced: 'Synchronisée',
    duplicating: 'Duplication…',
    duplicate: 'Dupliquer',
    relaunch: 'Relancer',
    noSetsForExercise: 'Aucune série enregistrée pour cet exercice.',
    noExerciseRecorded: 'Aucun exercice enregistré',
    exercisesNotYetEntered: "Les exercices de cette séance n'ont pas encore été saisis.",
    todayLabel: "Aujourd'hui",
    yesterdayLabel: 'Hier',
    thisWeekLabel: 'Cette semaine',
    thisMonthLabel: 'Ce mois-ci',
    allPeriod: 'Tout',
    thirtyDaysLabel: '30 jours',
    sevenDaysLabel: '7 jours',
    loadingHistory: "Chargement de l'historique...",
    noWorkoutFound: 'Aucune séance trouvée',
    tryOtherSearch: 'Essaie une autre recherche',
    newWorkoutBtn: 'Nouvelle séance',
    weeklyProgress: 'Progression hebdomadaire',
    chargesByExercise: 'Charges par exercice',
    workoutsFoundCount: '{count} séance{plural} trouvée{plural}',
    completedWorkoutsCount: '{count} séances terminées',
    avatarUploadError: "Impossible d'uploader l'avatar. Réessaie.",
    avatarDeleteTitle: "Supprimer l'avatar",
    avatarDeleteConfirm: 'Tu veux vraiment supprimer ta photo de profil ?',
    avatarDeleteError: "Impossible de supprimer l'avatar.",
    profilePhoto: 'Photo de profil',
    whatToDo: 'Que veux-tu faire ?',
    trackWorkoutNotFoundTitle: 'Séance introuvable',
    trackWorkoutNotFoundDesc: "Revenez à l'accueil pour créer ou sélectionner une séance.",
    trackBackToHome: "Retour à l'accueil",
    trackExerciseMeta: '{count} exercice',
    trackExercisesMeta: '{count} exercices',
    trackSetMeta: '{count} série',
    trackSetsMeta: '{count} séries',
    trackSetsHeader: '{completed}/{total} séries',
    trackRest: 'Repos',
    trackNoExerciseTitle: 'Aucun exercice',
    trackNoExerciseDesc: "Ajoute des exercices depuis l'écran de création pour commencer le suivi.",
    trackAddFirstSet: 'Ajoute ta première série',
    trackVideo: 'Vidéo',
    trackSet: 'Série',
    trackRepeat: 'Répéter',
    trackValidate: 'Valider',
    trackLongPress: 'Appui long',
    trackSetsValidated: 'séries validées',
    trackFinishWorkout: 'Terminer la séance',
    trackPendingSync: '{count} en attente de sync',
    trackOpenVideoError: "Impossible d'ouvrir la vidéo",
    trackReps: 'Reps',
    trackWeight: 'Poids',
    trackRpe: 'RPE',
    welcomeGorillax: '🦍 Bienvenue sur Gorillax !',
    configLater: 'Tu peux configurer ton profil plus tard dans les paramètres',
    accessApp: "Accéder à l'app",

    // Exercise progression
    rangeLabelWeek: '7 jours',
    rangeLabelMonth: '30 jours',
    rangeLabelAll: 'Tout',
    progressionDash: 'Progression',
    progressChartDesc: 'Charge totale (poids × reps) sur les séances contenant cet exercice.',
    progressMinSessions: 'Ajoute au moins trois séances avec cet exercice et des charges renseignées pour afficher la courbe de progression.',
    noSessionForExercise: 'Aucune séance enregistrée pour cet exercice.',

    // CreateWorkoutScreen
    selectedExercises: 'Exercices sélectionnés',
    addExercisesFromCatalog: 'Ajoute des exercices depuis le catalogue',
    searchExercisePlaceholder: 'Rechercher un exercice...',
    noExerciseFound: 'Aucun exercice trouvé',
    workoutReady: 'Séance prête !',
    exerciseCountAutoSave: '{count} exercice(s) • Sauvegarde auto',

    // Objective units (for unit selector display)
    unitDays: 'jours',

    // PersonalStats
    onlyXLeft: 'Plus que {count} !',

    // DemoTourModal
    demoTourStepIndicator: 'Étape {current}/{total}',
    demoTourSkip: 'Passer',
    demoTourAutoHint: 'Démo automatique • ~30 s',
    demoTourStep1Title: 'Accueil',
    demoTourStep1Desc: 'Ton tableau de bord : streak, objectif de la semaine et prochaine séance.',
    demoTourStep2Title: 'Créer une séance',
    demoTourStep2Desc: 'Donne un titre, ajoute des exercices, note tes séries (poids, reps) pendant l\'entraînement.',
    demoTourStep3Title: 'Mon Programme',
    demoTourStep3Desc: 'Organise tes semaines et lance une séance en un clic depuis ton programme.',
    demoTourStep4Title: 'Réseau (Feed)',
    demoTourStep4Desc: 'Vois les séances partagées, like, commente et consulte les profils.',
    demoTourStep5Title: 'Explorer & Défis',
    demoTourStep5Desc: 'Rejoins des défis communautaires et compare-toi aux autres.',
    demoTourStep6Title: 'Messages',
    demoTourStep6Desc: 'Échange en privé avec d\'autres membres depuis l\'onglet Messages.',
    demoTourStep7Title: 'Profil & Paramètres',
    demoTourStep7Desc: 'Gère ton profil, tes stats, les réglages et déconnecte-toi si besoin.',
    demoTourStep8Title: 'C\'est parti !',
    demoTourStep8Desc: 'Tu connais les bases. Bonne séance avec Gorillax 🦍',

    // ErrorBoundary
    errorBoundaryTitle: 'Oups, quelque chose a planté',
    errorBoundaryMessage: 'Une erreur inattendue est survenue.',

    // ProgressCard
    totalSessions: 'Total séances',
    kgLifted: 'Kg soulevés',
    ofGoal: "de l'objectif",
    weeklyGoalReached: 'Objectif de la semaine atteint !',
    startFirstSession: 'Commence ta première séance pour voir tes stats ici',
    sessionsOfGoal: '{current}/{goal} séances',

    // Shared screen strings
    viewDetails: 'Voir détails',
    plannedSets: 'Séries prévues',
    createYourWorkout: 'Créer ta séance',
    workoutNameSection: 'Nom de la séance',
    workoutNamePlaceholder: 'Ex: Push Day, Jambes...',
    watchVideo: 'Voir la vidéo',
    notEnoughData: 'Pas assez de données',
    sessionHistory: 'Historique des séances',

    // ExerciseChargesChart
    sessionCount: '{count} séance(s)',

    // useAuth errors
    errorFetchProfile: 'Impossible de récupérer le profil utilisateur',
    errorConnection: 'Erreur de connexion',
    errorWrongCredentials: 'Nom d\'utilisateur ou mot de passe incorrect',
    errorServerTimeout: 'Le serveur met trop de temps à répondre. Réessaie dans quelques secondes (serveur au réveil).',
    errorDemoConnection: 'Impossible de se connecter au compte demo',
    errorServerTimeoutShort: 'Le serveur met trop de temps à répondre. Réessaie dans quelques secondes.',
    errorRegistration: 'Erreur d\'inscription',
    errorRegistrationGeneric: 'Erreur lors de l\'inscription',

    // CreateWorkoutScreen
    noWorkoutSelected: 'Aucune séance sélectionnée',
    noWorkoutSelectedDesc: "Crée une nouvelle séance depuis l'accueil pour commencer ton entraînement.",
    composeCustomWorkout: 'Compose ton entraînement sur mesure',
    catalogTitle: 'Catalogue',
    variousMuscles: 'Muscles variés',
    freeEquipment: 'Matériel libre',
    noDescriptionYet: 'Pas encore de description enregistrée.',
    detailedSheet: 'Fiche détaillée',

    // HistoryScreen extra
    errorOccurred: 'Une erreur est survenue',
    stableLabel: 'Stable',
    syncLabel: 'Sync',

    // HistoryDetailScreen
    sessionNotFound: 'Séance introuvable',
    returnToHistoryDesc: 'Retourne à l\'historique pour sélectionner une séance valide.',
    backToHistory: 'Revenir à l\'historique',
    duplicationFailed: 'Duplication impossible',
    duplicationFailedDesc: 'Nous ne parvenons pas à dupliquer cette séance pour le moment.',
    duplicationErrorDesc: 'Une erreur est survenue lors de la duplication. Réessaie plus tard.',
    connectToShareDesc: 'Connecte-toi pour partager ta séance sur le feed.',
    syncInProgress: 'Synchronisation en cours',
    retryInFewSeconds: 'Réessaie dans quelques secondes.',
    repCount: '{count} répétition(s)',

    // Premium / Paywall
    premiumActivated: 'Premium activé !',
    premiumActivatedDesc: 'Tu as maintenant accès à toutes les fonctionnalités.',
    error: 'Erreur',
    purchaseError: 'Impossible de finaliser l\'achat.',
    restored: 'Achat restauré',
    restoredDesc: 'Ton abonnement a été restauré avec succès.',
    restoreError: 'Impossible de restaurer. Vérifie ton compte App Store / Play Store.',
    featureUnlimitedPrograms: 'Programmes IA illimités',
    featureAdvancedStats: 'Statistiques avancées & progression',
    featureFullHistory: 'Historique complet sans limite',
    featureUnlimitedObjectives: 'Objectifs personnalisés illimités',
    featurePriority: 'Accès prioritaire aux nouvelles fonctionnalités',
    paywallSubtitle: 'Débloque tout le potentiel de Gorillax pour atteindre tes objectifs plus vite.',
    bestValue: 'Meilleur prix',
    yearlyPlan: 'Annuel',
    monthlyPlan: 'Mensuel',
    perYear: '€/an',
    perMonth: '€/mois',
    save33: '-33%',
    subscribe: 'S\'abonner',
    restorePurchases: 'Restaurer les achats',
    subscriptionLegal: 'L\'abonnement se renouvelle automatiquement. Tu peux annuler à tout moment depuis les réglages de ton store.',
    premiumFeature: 'Fonctionnalité Premium',
    upgradeToPremium: 'Passer à Premium',
    subscriptionLabel: 'Abonnement',
    currentPlan: 'Plan actuel',
    freePlan: 'Gratuit',
    premiumPlan: 'Premium',
    manageSubscription: 'Gérer mon abonnement',
    expiresOn: 'Expire le',
  },
  en: {
    // Navigation
    home: 'Home',
    explore: 'Explore',
    feed: 'Feed',
    messages: 'Messages',
    profile: 'Profile',
    menu: 'Menu',
    
    // Stats et données
    lastWorkout: 'Last workout',
    thisWeek: 'This week',
    sessions: 'sessions',
    completed: 'completed',
    streak: 'Streak',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: '{days}d ago',
    getBackToIt: 'Get back to it!',
    itsBeenAWhile: 'It\'s been a while...',
    goalReached: 'Goal reached! 🎯',
    newRecord: 'New record! 🔥',
    personalRecord: 'Personal record',
    progression: 'Progression',
    level: 'Level',
    
    // Sections principales
    quickActions: 'Quick actions',
    myWorkouts: 'My workouts',
    lastCreatedWorkout: 'Last created workout',
    draftInProgress: 'Draft in progress',
    lastCompletedWorkout: 'Last completed workout',
    completedSession: 'Completed session',
    
    // États vides
    noWorkoutInProgress: 'No workout in progress',
    createFirstWorkout: 'Create your first workout to get started',
    noCompletedWorkout: 'No completed workout',
    completeWorkoutToSee: 'Complete a workout to see it here',

    // Welcome empty state
    welcome: 'Welcome',
    welcomeEmpty: "Time to start your fitness journey. Create your first workout to track your progress!",
    createMyFirstWorkout: 'Create my first workout',
    discoverPrograms: 'Discover programs',
    tipCreateTitle: 'Create',
    tipCreateDesc: 'Build your workout with your exercises',
    tipTrackTitle: 'Progress',
    tipTrackDesc: 'Track your stats and beat your records',

    // Actions
    createWorkout: 'Create workout',
    newWorkout: 'New workout',
    newProgram: 'New program',
    drafts: 'Drafts',
    seeAll: 'See all',
    defaultWorkoutTitle: 'Workout',
    feedWorkoutTitle: 'Feed workout',
    workoutCopy: '{title} (copy)',
    workoutCopyN: '{title} (copy {n})',
    errorWorkoutNotFound: 'Workout not found',
    errorProfileUnavailable: 'User profile unavailable',
    errorWorkoutNotSynced: 'Workout not synced yet. Wait a few seconds and try again.',
    errorFeedLoad: 'Unable to load feed',
    
    // Settings
    settings: 'Settings',
    appearance: 'Appearance',
    languageAndRegion: 'Language & Region',
    preferences: 'Preferences',
    language: 'Language',
    units: 'Units',
    unitSystem: 'Unit system',
    accentColor: 'Accent color',
    heroColor: 'Header color',
    darkMode: 'Dark mode',
    darkModeDescription: 'Dark interface for your eyes',
    french: 'Français',
    english: 'English',
    metric: 'Metric',
    imperial: 'Imperial',
    
    // Informations
    basicInfo: 'Basic information',
    personalInfo: 'Personal information',
    fitnessGoals: 'Fitness goals',
    username: 'Username',
    bio: 'Bio',
    mainGoal: 'Main goal',
    location: 'Location',
    height: 'Height',
    weight: 'Weight',
    
    // Navigation drawer
    history: 'History',
    objectives: 'Objectives',
    parameters: 'Settings',
    
    // Unités
    kg: 'kg',
    lbs: 'lbs',
    cm: 'cm',
    ft: 'ft',
    
    // Messages d'état
    loading: 'Loading...',
    loadingSettings: 'Loading settings...',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    error: 'Error',
    
    // Greetings and motivational messages
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    consecutiveDays: 'consecutive days',
    daysInARow: 'days in a row',
    readyForWorkout: 'Ready for your workout?',
    letsGo: 'Let\'s go!',
    
    // Experience levels
    beginner: 'Beginner',
    beginnerDesc: 'Less than 6 months',
    intermediate: 'Intermediate',
    intermediateDesc: '6 months - 2 years',
    advanced: 'Advanced',
    advancedDesc: 'More than 2 years',
    
    // Objectives
    muscleGain: 'Muscle gain',
    weightLoss: 'Weight loss',
    strength: 'Strength',
    endurance: 'Endurance',
    generalFitness: 'General fitness',
    sportSpecific: 'Sport specific',
    
    // Equipment
    dumbbells: 'Dumbbells',
    barbell: 'Olympic barbell',
    machines: 'Machines',
    kettlebells: 'Kettlebells',
    bands: 'Resistance bands',
    bodyweight: 'Bodyweight',
    trx: 'TRX',
    bench: 'Bench',
    squat_rack: 'Squat rack',
    cardio: 'Cardio (treadmill, bike...)',
    
    // Gender
    male: 'Male',
    female: 'Female',
    other: 'Other',
    preferNotToSay: 'Prefer not to say',
    
    // Form labels and descriptions
    yourUsername: 'Your username',
    tellAboutYou: 'Tell us about yourself...',
    locationPlaceholder: 'Paris, France',
    heightCm: 'Height (cm)',
    weightKg: 'Weight (kg)',
    heightPlaceholder: '175',
    weightPlaceholder: '70',
    gender: 'Gender',
    experienceLevel: 'Experience level',
    trainingFrequency: 'Training frequency (times per week)',
    availableEquipment: 'Available equipment',
    publicShare: 'Public sharing',
    publicShareDesc: 'Allow public sharing of your workouts',
    saveCompleteProfile: 'Save complete profile',
    guideTitle: 'User guide',
    guideUsage: 'View guide and explanations',
    demoButton: 'Start demo (30 s)',
    actions: 'Actions',
    logout: 'Logout',
    logoutConfirm: 'Are you sure you want to logout?',
    logoutButton: 'Logout',
    version: 'Gorillax v1.0.0',
    
    // Error messages
    usernameRequired: 'Username cannot be empty',
    usernameTaken: 'This username is already taken',
    cannotSaveInfo: 'Unable to save information',
    cannotSaveProfile: 'Unable to save complete profile',
    profileSaved: '✅ Information updated!',
    profileCompleteSaved: '✅ Complete profile saved!',
    goalError: 'Goal must be between 1 and 14 sessions per week.',
    cannotSaveGoal: 'Unable to save goal.',
    weeklyGoal: 'Weekly goal',
    howManySessionsPerWeek: 'How many sessions do you want to do per week?',

    // General UI
    defaultUser: 'User',
    untitled: 'Untitled',
    delete: 'Delete',
    info: 'Info',
    total: 'Total',

    // Profile
    noBioDefined: 'No bio defined',
    editProfile: 'Edit profile',
    profileUpdated: '✅ Profile updated!',
    avatarUploadComingSoon: 'Avatar upload feature coming soon!',
    photoPermissionDesc: 'Allow access to your photos to change your avatar.',
    permissionRequired: 'Permission required',
    objectiveLabel: 'Goal',
    objectivePlaceholder: 'E.g.: Muscle gain, Weight loss...',
    sessionsLabel: 'Sessions',
    exercisesLabel: 'Exercises',
    setsLabel: 'sets',

    // Navigation/Menu items
    myPublicProfile: 'My public profile',
    memberCard: 'Member card / Gym pass',
    myProgram: 'My Program',
    myObjectives: 'My Objectives',
    notifications: 'Notifications',
    termsOfUse: 'Terms of use',
    privacyLabel: 'Privacy',
    settingsSection: 'Settings',
    createProgram: 'Create a program',
    progressionNav: 'Progression',

    // QuickStats explanations
    objectiveExplanation: 'Number of sessions completed this week compared to your goal of {goal} sessions per week.',
    volumeKg: 'Volume (kg)',
    volumeExplanation: 'Total volume lifted this week (weight × reps). Compared to the previous week.',
    streakExplanation: 'Consecutive days with at least one completed session. Keep going to maintain your streak!',
    draftsExplanation: 'Workouts being created or pending.',
    completedLabel: 'Completed',
    completedExplanation: 'Fully completed and recorded workouts.',

    // Milestones
    sessionsCount: '{count} sessions',
    daysInARowCount: '{count} days in a row',
    volumeThisWeek: 'Volume this week',
    startWorkout: 'Start a workout',
    sessionsPerMonth: 'Sessions per month',

    // Pass / Wallet
    passDescription: 'Show this pass at the entrance or on the machine at a Gorillax partner gym.',
    loginRequired: 'Login required',
    loginToAddPass: 'Log in to add the pass.',
    addToAppleWallet: 'Add to Apple Wallet',
    addToGoogleWallet: 'Add to Google Wallet',
    googleWalletLink: 'Google Wallet link',
    memberCardTitle: 'Member card',
    gorillaxMemberCard: 'Gorillax member card',
    cannotOpenPass: 'Unable to open the pass. Check your connection.',
    notConfigured: 'Not configured',
    googleWalletNotConfigured: 'Google Wallet is not yet configured on this server.',
    cannotOpenGoogleWallet: 'Unable to open Google Wallet. Check your connection.',
    openLink: 'Open link',
    openInSafari: 'Open this link in Safari to add the pass.',

    // Messages
    workoutLabelSingle: 'Workout',
    viewWorkout: 'View workout',
    onlineStatus: 'Online',
    startConversation: 'Start the conversation',
    sendFirstMessageTo: 'Send your first message to {name}',
    writeMessage: 'Write a message...',

    // Share post
    newPost: 'New post',
    publish: 'Publish',
    previewLabel: 'Preview',
    myWorkout: 'My workout',
    descriptionLabel: 'Description',
    describeWorkout: 'Describe your workout, your feelings, your progress...',
    colorLabel: 'Color',
    photoLabel: 'Photo',
    changePhoto: 'Change photo',
    addPhoto: 'Add a photo',
    tapToReplace: 'Tap to replace',
    fromGallery: 'From your gallery',
    photoPermissionMessage: 'Allow access to your gallery to add a photo.',
    cannotPublish: 'Unable to publish.',

    // Leaderboard
    rankings: 'Rankings',
    followersLabel: 'Followers',
    sevenDays: '7 days',
    thirtyDays: '30 days',
    allTime: 'All time',
    youLabel: 'You',
    placeLabel: 'place',
    placesLabel: 'places',
    yourRankIs: "You're #{rank} in the rankings!",
    rankingSection: 'RANKING',
    noRankingYet: 'No rankings yet',
    shareToAppear: 'Share your workouts to appear here!',
    challengesTab: 'Challenges',
    activeChallenges: 'Active challenges',
    moreChallengesSoon: 'More challenges soon',
    moreChallengesSoonDesc: 'New challenges will be added regularly. Stay tuned!',
    leaderVolume: 'Volume',
    leaderSessions: 'Sessions',
    leaderLikes: 'Likes',
    leaderFollowers: 'Followers',

    // Notifications
    justNow: 'Just now',
    commentLabel: 'Comment',
    subscriptionLabel: 'Subscription',
    mentionLabel: 'Mention',
    notificationLabel: 'Notification',
    olderLabel: 'Older',
    someone: 'Someone',
    noNotifications: 'No notifications',
    notificationEmptyDesc: "You'll receive notifications when someone interacts with your workouts",
    exploreFeed: 'Explore the feed',
    likesLabel: 'Likes',
    commentsLabel: 'Comments',
    deleteAction: 'Delete',
    markAsRead: 'Mark as read',
    notificationActions: 'Actions',
    clearAllNotifications: 'Clear all',
    clearAllNotificationsDesc: 'Delete all notifications? This action cannot be undone.',
    clearAll: 'Clear all',
    allFilter: 'All',
    followsFilter: 'Follows',
    noNotificationsForFilter: 'No notifications of this type',
    notificationFilterEmptyDesc: "You haven't received this type of notification yet.",
    showAllNotifications: 'Show all notifications',

    // Library
    thisMonth: 'This month',
    deleteWorkoutTitle: 'Delete workout',
    confirmDeleteWorkout: 'Do you really want to delete "{title}"?',
    minutesAgo: '{n}min ago',
    hoursAgo: '{n}h ago',
    doneLabel: 'Done',
    inProgressLabel: 'In progress',
    setsProgress: '{completed}/{total} sets',
    completedStatus: 'Completed',
    viewLabel: 'View',
    startLabel: 'Start',
    myLibrary: 'My Library',
    totalWorkoutsCount: '{count} total workouts',
    searchWorkout: 'Search a workout...',
    newSession: 'New workout',

    // Explore
    searchPlaceholder: 'Search...',
    allCategory: 'All',
    forceCategory: 'Strength',
    cardioCategory: 'Cardio',
    massCategory: 'Mass',
    lossCategory: 'Loss',
    trendingSection: 'Trending',
    suggestedSection: 'Suggested',
    challengesSection: 'Challenges',
    follow: 'Follow',
    following: 'Following',

    // Programme
    generateProgram: 'Generate a program',
    programObjective: 'Program objective',
    frequency: 'Frequency',
    timesPerWeek: 'times per week',
    exercisesPerSession: 'Exercises per session',
    duration: 'Duration',
    weeks: 'weeks',
    hypertrophy: 'Hypertrophy',
    cutting: 'Cutting',
    forceLabel: 'Strength',
    recomposition: 'Recomposition',
    wellBeing: 'Well-being',
    myPrograms: 'My programs',
    noPrograms: 'No programs',
    createFirstProgram: 'Create your first personalized program',
    programSaved: 'Program saved!',
    cannotGenerateProgram: 'Unable to generate the program.',
    cannotSaveProgram: 'Unable to save the program.',
    importToWorkouts: 'Import to my workouts',
    saveProgram: 'Save program',
    programImported: 'Program imported to your workouts!',

    // Register
    createAccount: 'Create an account',
    usernamePlaceholder: 'Username',
    emailPlaceholder: 'Email',
    passwordPlaceholder: 'Password',
    confirmPasswordPlaceholder: 'Confirm password',
    alreadyHaveAccount: 'Already have an account?',
    loginLink: 'Log in',
    registerButton: 'Sign up',
    createYourAccount: 'Create your account',
    usernameLabel: 'Username',
    chooseUsername: 'Choose a username',
    emailLabel: 'Email',
    emailExample: 'your@email.com',
    passwordLabel: 'Password',
    passwordMinChars: 'At least 8 characters',
    confirmPasswordLabel: 'Confirm password',
    repeatPassword: 'Repeat your password',
    fillAllFields: 'Please fill in all fields',
    usernameMinLength: 'Username must be at least 3 characters',
    invalidEmail: 'Please enter a valid email address',
    passwordMinLength: 'Password must be at least 8 characters',
    passwordsDoNotMatch: 'Passwords do not match',
    registrationError: 'Error during registration',

    // Explore extra
    exploreTitle: 'Explore',
    discoverWorkouts: 'Discover inspiring workouts',
    searchWorkoutsUsers: 'Search workouts, users...',
    participate: 'Participate',
    usersSection: 'Users',
    workoutsSection: 'Workouts',
    noResults: 'No results',
    noResultsFor: 'No results for',
    searchInProgress: 'Searching...',
    toDiscover: 'Discover',
    seeAllLabel: 'See all',
    challengesOfMoment: 'Current challenges',
    nothingToExplore: 'Nothing to explore yet',
    communityWorkoutsWillAppear: 'Workouts shared by the community will appear here',
    createSession: 'Create a workout',
    noSessionFound: 'No workout found',
    noSessionForCategory: 'No workout',
    forTheMoment: 'at the moment',
    seeEverything: 'See all',
    loadingText: 'Loading...',
    subscriberCount: 'follower',
    subscribersCount: 'followers',
    exosCount: 'exercises',

    // Objectives extra
    sessionsPerWeekTitle: 'Sessions per week',
    sessionsPerWeekDesc: 'Number of sessions to complete each week',
    weeklyVolumeTitle: 'Weekly volume',
    weeklyVolumeDesc: 'Total weight lifted per week',
    sessionsPerMonthTitle: 'Sessions per month',
    sessionsPerMonthDesc: 'Monthly session goal',
    dayStreakTitle: 'Day streak',
    dayStreakDesc: 'Number of consecutive days with a session',
    squatRecordTitle: 'Squat record',
    squatRecordDesc: 'Maximum squat weight',
    benchRecordTitle: 'Bench press record',
    benchRecordDesc: 'Maximum bench press weight',
    sessionsUnit: 'sessions',
    daysUnit: 'days',
    cannotSaveObjectives: 'Unable to save objectives.',
    enterValidValue: 'Please enter a valid value.',
    fillRequiredFields: 'Please fill in all required fields.',
    enterValidTarget: 'Please enter a valid target value.',
    deleteObjectiveTitle: 'Delete objective',
    deleteObjectiveConfirm: 'Do you really want to delete "{title}"?',
    deleteLabel: 'Delete',
    cancelLabel: 'Cancel',
    editObjectiveTitle: 'Edit objective',
    goalInUnit: 'Goal in {unit}',
    saveLabel: 'Save',
    newObjectiveTitle: 'New objective',
    titleRequired: 'Title *',
    titlePlaceholder: 'E.g.: Deadlift record',
    objectiveDescriptionPlaceholder: 'Objective description',
    targetRequired: 'Goal *',
    unitLabel: 'Unit',
    colorLabelObj: 'Color',
    createLabel: 'Create',
    defineGoalsAndTrack: 'Set your goals and track your progress',

    // Programme create extra
    createProgramTitle: 'Create a program',
    customizeTraining: 'Customize your training according to your goals',
    objectiveSection: 'Objective',
    hypertrophyLabel: 'Hypertrophy',
    forceOptionLabel: 'Strength',
    enduranceLabel: 'Endurance',
    fitnessLabel: 'Fitness',
    massGainDesc: 'Mass gain',
    maxPowerDesc: 'Max power',
    muscularCardioDesc: 'Muscular cardio',
    fitnessDesc: 'Get in shape',
    suggestionsBasedOnProfile: 'Suggestions based on your profile',
    smartPersonalization: 'Smart personalization',
    suggestedObjective: 'Suggested objective:',
    suggestedLevel: 'Suggested level:',
    suggestedFrequency: 'Suggested frequency:',
    applyLabel: 'Apply',
    suggestionsNote: 'These suggestions are based on your profile information',
    parametersSection: 'Parameters',
    frequencyLabel: 'Frequency',
    perSessionLabel: 'Per session',
    durationLabel: 'Duration',
    sessionLabel: 'Session',
    levelSection: 'Level',
    beginnerLevel: 'Beginner',
    intermediateLevel: 'Intermediate',
    advancedLevel: 'Advanced',
    methodSection: 'Method',
    autoMethod: 'Auto',
    optimalChoice: 'Optimal choice',
    fullBody: 'Full Body',
    wholeBody: 'Whole body',
    upperLower: 'Upper/Lower',
    upperLowerDesc: 'Upper/Lower',
    pplMethod: 'PPL',
    pplDesc: 'Push/Pull/Legs',
    equipmentSection: 'Equipment',
    selectedCount: 'selected',
    selectedPluralCount: 'selected',
    barreLabel: 'Barbell',
    dumbbellsLabel: 'Dumbbells',
    bodyweightLabel: 'Bodyweight',
    machinesLabel: 'Machines',
    cablesLabel: 'Cables',
    kettlebellLabel: 'Kettlebell',
    constraintsSection: 'Constraints',
    constraintsPlaceholder: 'E.g.: Fragile knee, sensitive back...',
    howItWorksTitle: 'How does it work?',
    howItWorksSubtitle: 'Our algorithm builds your program based on sports science',
    howItWorks1Title: 'Adapted volume',
    howItWorks1Desc: 'Sets per muscle are calculated based on your level, following scientific recommendations (10-20 sets/week per muscle).',
    howItWorks2Title: 'Compounds first',
    howItWorks2Desc: 'Each session starts with compound exercises (squat, bench, rows...) then isolations. This is the most effective method.',
    howItWorks3Title: 'Built-in progression',
    howItWorks3Desc: 'Volume and intensity increase week over week. Programs of 5+ weeks automatically include a deload week.',
    howItWorks4Title: 'Smart rep ranges',
    howItWorks4Desc: 'Compounds use heavier rep ranges (6-8), accessories moderate (8-12), and isolations lighter (12-15). Adapted to your goal.',
    frequencyHelper: 'Each muscle should be trained at least 2x/week. 3-4x is ideal for most people.',
    durationHelper: '4 weeks = 1 mesocycle. 5+ weeks = automatic deload.',
    sessionDurationHelper: '45-60 min is optimal. Beyond 75 min, performance drops.',
    levelHelper: 'Your level determines set volume and exercise complexity.',
    methodHelper: 'Auto mode picks the optimal split based on your frequency.',
    generationInProgress: 'Generating...',
    generateMyProgram: 'Generate my program',
    generationImpossible: 'Generation impossible',
    programNotFound: 'Program not found',
    loginRequiredToSave: 'You must be logged in to save sessions.',
    connectionRequired: 'Login required',
    sessionsRegistered: 'Sessions saved!',
    sessionRegisteredCount: '{count} session saved.',
    sessionsRegisteredCount: '{count} sessions saved.',
    cannotSave: 'Unable to save',
    emptySession: 'Empty session',
    sessionHasNoSets: 'This session has no sets.',
    cannotCreateSession: 'Unable to create session',
    cannotStart: 'Unable to start',
    sportMode: 'Sport',
    startSession: 'Start',
    exerciseMore: 'exercise',
    exercisesMore: 'exercises',
    repsLabel: 'reps',
    rpeLabel: 'RPE',
    seeDetails: 'See details',
    hideDetails: 'Hide',
    savingInProgress: 'Saving...',
    saveAllSessions: 'Save all sessions',
    savedBadge: 'Saved',
    sessionsLabel2: 'sessions',
    semLabel: 'wk',

    // Programme index extra
    myProgramsTitle: 'My Programs',
    createYourFirstProgram: 'Create your first program',
    loadingPrograms: 'Loading programs...',
    cannotLoadPrograms: 'Unable to load programs',
    errorTitle: 'Error',
    retryLabel: 'Retry',
    createProgramButton: 'Create a program',
    programsCount: 'program',
    programsCountPlural: 'programs',
    emptyProgramDesc: 'Create your first personalized program to organize your workouts',
    generalLabel: 'General',
    sessionsCountLabel: 'sessions',
    emptySessionAlert: 'Empty session',
    emptySessionAlertDesc: 'This session has no sets.',
    cannotStartSession: 'Unable to start session',

    // Login
    loginTitle: 'Log in to your account',
    yourPassword: 'Your password',
    loginButton: 'Log in',
    demoLoginButton: 'Try with the Demo account',
    notRegisteredYet: 'Not registered yet? Create an account',
    connectionError: 'Connection error',
    demoConnectionError: 'Unable to connect to demo account',

    // Messages tab
    conversations: 'Conversations',
    unreadLabel: 'Unread',
    noMessage: 'No message',
    noConversation: 'No conversation',
    startChattingDesc: 'Start chatting with other athletes!',
    newConversation: 'New conversation',
    loadDemoConversations: 'Load demo conversations',
    yourConversations: 'YOUR CONVERSATIONS',

    // Profile basic page
    myProfileTitle: 'My profile',
    profilePageDesc: 'Choose a username and indicate if you allow your shared workouts to be public.',
    pseudo: 'Username',
    sharePublicly: 'Share publicly',
    sharePubliclyDesc: 'Enable this setting to allow your shared workouts to appear in the feed.',
    pseudoRequired: 'Username required',
    enterPseudo: 'Please enter a username.',
    profileRegistered: 'Profile saved',
    preferencesUpdated: 'Your preferences have been updated.',
    savingFailed: 'Unable to save',
    retryLater: 'Try again later.',
    loadingProfile: 'Loading profile...',
    accountSection: 'Account',
    loggedInAs: 'Logged in as:',
    disconnectLabel: 'Logout',
    disconnectTitle: 'Logout',

    // Library extra
    daysAgoShort: '{n}d ago',

    // Shared workout detail
    workoutNotFound: 'Workout not found',
    loadingError: 'Loading error',
    sharedWorkout: 'Shared workout',
    back: 'Back',
    setLabel: 'Set',
    weightHeader: 'Weight',
    repsHeader: 'Reps',
    totalVolume: 'Total volume',
    exercisesCount: '{count} exercises',
    setsCount: '{count} sets',

    // Profile [id] page
    profileNotFound: 'Profile not found',
    profileNotFoundDesc: "This profile doesn't exist or has been deleted",
    noBio: 'No bio',
    likesReceived: '{count} Likes received',
    editProfileLabel: 'Edit profile',
    noSharedWorkout: 'No shared workout',
    noSavedPost: 'No saved post',
    sharedWorkoutsWillAppear: 'Your shared workouts will appear here',
    savedPostsWillAppear: 'Saved posts will appear here',
    profileNotSharedYet: "This profile hasn't shared any workout yet",
    postsTab: 'Posts',
    savedTab: 'Saved',
    subscribersLabel: 'Followers',
    followingCountLabel: 'Following',
    messageLabel: 'Message',
    followedLabel: 'Following',

    // Profile setup
    tellAboutYourself: 'Tell us about yourself',
    personalizeExperience: 'This information will help us personalize your experience',
    bioOptional: 'Bio (optional)',
    describeBriefly: 'Describe yourself briefly...',
    locationOptional: 'Location (optional)',
    genderOptional: 'Gender (optional)',
    fitnessObjectives: 'Your fitness goals',
    adaptedPrograms: 'Help us create adapted programs',
    mainObjective: 'Main objective',
    desiredFrequency: 'Desired training frequency',
    preferencesTitle: 'Preferences',
    lastStepPersonalize: 'Last step to personalize your experience',
    consentPublicShare: 'I agree to share my workouts publicly',
    canChangeSettingsLater: 'You can change this setting at any time in the settings',
    stepOf: 'Step {current} of {total}',
    saving: 'Saving...',
    finish: 'Finish',
    next: 'Next',
    skipForNow: 'Skip for now',
    testFinish: 'Test Finish',

    // Feed
    feedLoading: 'Loading feed...',
    feedEmptyTitle: 'Your feed is empty',
    feedEmptySubtitle: 'Follow other users to see their workouts and share yours!',
    loadMorePosts: 'Load more posts',
    feedUpToDate: "You're up to date!",
    commentsTitle: 'Comments',
    noCommentsYet: 'No comments yet',
    beFirstToComment: 'Be the first to comment on this workout!',
    addCommentPlaceholder: 'Add a comment...',

    // Messages chat
    workoutFallback: 'Workout',
    sharedWorkoutLabel: 'Shared workout',

    // Messages new
    newConversationTitle: 'New conversation',
    searchUserPlaceholder: 'Search for a user...',
    searching: 'Searching...',
    findAthlete: 'Find an athlete',
    searchByUsername: 'Search by username to start a conversation',
    noUserFoundFor: 'No user found for "{query}"',
    resultCountLabel: '{count} RESULT(S)',
    creatingConversation: 'Creating...',

    // Page headers
    sessionDetail: 'Session detail',
    sessionTracking: 'Session tracking',

    // Leaderboard
    sessionsTabLabel: 'Sessions',
    followersTabLabel: 'Followers',
    allTimePeriod: 'All',

    // Guide
    guideIntro: 'Discover how to get the most out of Gorillax: workout tracking, programs, social feed and more.',
    guideHomeTitle: 'Home',
    guideHomeContent: 'On the Home tab you see your dashboard: your streak (consecutive days), weekly goal (e.g. 3/4 workouts) and your next workout. Use the menu (hamburger icon) to access Progress, My Program and Settings. You can start a workout in one tap from the "Next workout" card.',
    guideCreateTitle: 'Create and do a workout',
    guideCreateContent: 'From the home screen or menu, choose "Create a workout". Give it a title (e.g. Push Day), add exercises from the library (search by name). During your workout, log your sets: weight, reps, RPE. The timer between sets helps you keep the pace. When you\'re done, mark the workout as completed: it will be saved in your history and progress.',
    guideProgramTitle: 'My Program',
    guideProgramContent: 'In My Program you organize your weeks: you see your workouts by day. Click on a workout to launch it. You can also create a new program (Create a program) to plan several weeks ahead.',
    guideFeedTitle: 'Network (Feed)',
    guideFeedContent: 'The Network tab shows the feed: workouts shared by the community. You can like a post (heart), comment, and click on a username to see the public profile (stats, bio, workouts). The leaderboard (volume, frequency) is accessible from the feed to compare yourself to others.',
    guideExploreTitle: 'Explore and challenges',
    guideExploreContent: 'In the Explore tab you discover community challenges. Open a challenge to see the rules and rewards, then join it. You can also search for workouts or users from the search bar.',
    guideMessagesTitle: 'Messages',
    guideMessagesContent: 'The Messages tab lists your conversations. Open a conversation or create a new message to chat privately with another member. You can also send a message from a user\'s profile (the "Send a message" button).',
    guideProfileTitle: 'Profile and settings',
    guideProfileContent: 'On your Profile you see your avatar, username, bio, goal and your stats (workouts, exercises). From the profile menu: My public profile, Progress, My Program, My Goals, Notifications. Settings give access to Preferences (info, appearance, language), Terms of Use and Privacy. The Logout button takes you back to the login screen.',
    guideFooter: 'Great workout with Gorillax',

    // Explore challenges
    challenge100Pushups: '100 pushups',
    challenge100PushupsDesc: '100 pushups in 1 day',
    challenge7Days: '7-day challenge',
    challenge7DaysDesc: '7 workouts in 7 days',
    challengePRSquad: 'PR Squad',
    challengePRSquatDesc: 'Beat your squat PR',
    challengeCardioMaster: 'Cardio Master',
    challengeCardioMasterDesc: '30min cardio/day',

    // WorkoutCard
    viewAction: 'View',
    continueAction: 'Continue',
    startAction: 'Start',
    untitledWorkout: 'Untitled workout',

    // Demo
    demoHomeTitle: 'Home',
    demoHomeDesc: 'Your dashboard: streak, weekly goal and next workout. The menu (☰) gives access to progress and programs.',
    demoFeedTitle: 'Network (Feed)',
    demoFeedDesc: 'Workouts shared by the community. Like (❤️) and comment on posts.',
    demoExploreTitle: 'Explore',
    demoExploreDesc: 'Community challenges and workout discovery. Join a challenge to compete with others.',
    demoMessagesTitle: 'Messages',
    demoMessagesDesc: 'Your private conversations with other members.',
    demoProfileTitle: 'Profile',
    demoProfileDesc: 'Your stats, your menu (Progress, Program, Goals, Settings) and logout.',
    demoFinishTitle: "Let's go!",
    demoFinishDesc: "You've seen the essentials. Create a workout from the menu, follow your program and share on the feed. Great workout 🦍",

    // FeedCard
    reportPostTitle: '🚨 Report this post',
    reportPostWhy: 'Why are you reporting this post?',
    inappropriateContent: 'Inappropriate content',
    spam: 'Spam',
    harassment: 'Harassment',
    reportThanksTitle: '✅ Thank you',
    reportThanksMsg: 'Your report has been sent. We will review this post.',
    report: 'Report',
    hide: 'Hide',
    hideSeeNoMore: "Don't show this post anymore",
    exercises: 'exercises',
    sets: 'sets',
    saved: 'Saved',
    likesCount: 'like',
    sharedWorkoutDefault: 'shared a workout 💪',
    viewCommentsCount: 'View all {count} comment{plural}',
    addComment: 'Add a comment...',
    sendTo: 'Send to...',
    noUserFound: 'No user found',
    retry: 'Retry',

    // NextWorkoutCard
    launchAction: 'Start',
    exercisesMinFormat: '{count} exercises • {duration} min',

    // Challenge detail
    challengeHeader: 'Challenge',
    backLabel: 'Back',
    challengeNotFound: 'Challenge not found',
    challengeJoinedTitle: '🎉 Joined!',
    challengeJoinedMsg: 'You are now participating in the "{title}" challenge. Good luck!',
    challengeJoinedBtn: "Let's go!",
    challengeLeaveTitle: 'Leave the challenge?',
    challengeLeaveMsg: 'You will lose your progress if you leave now.',
    challengeLeaveBtn: 'Leave',
    difficultyEasy: 'Easy',
    difficultyMedium: 'Medium',
    difficultyHard: 'Hard',
    participantsLabel: 'participants',
    rulesLabel: 'Rules',
    rewardsLabel: 'Rewards',
    challengeParticipating: 'You are participating in this challenge',
    challengeLeave: 'Leave the challenge',
    challengeJoin: 'Join the challenge',

    // History screens
    statusCompleted: 'Completed',
    statusDraft: 'Draft',
    setValidated: 'Done',
    setPlanned: 'Planned',
    validatedOn: 'Done on {date}',
    exerciseLabel: 'exercise',
    serieLabel: 'set',
    seriesLabel: 'sets',
    validatedSets: 'Completed sets',
    estimatedDuration: 'Estimated duration',
    notAvailable: 'Not available',
    synced: 'Synced',
    duplicating: 'Duplicating…',
    duplicate: 'Duplicate',
    relaunch: 'Restart',
    noSetsForExercise: 'No sets recorded for this exercise.',
    noExerciseRecorded: 'No exercise recorded',
    exercisesNotYetEntered: 'Exercises for this session have not been entered yet.',
    todayLabel: 'Today',
    yesterdayLabel: 'Yesterday',
    thisWeekLabel: 'This week',
    thisMonthLabel: 'This month',
    allPeriod: 'All',
    thirtyDaysLabel: '30 days',
    sevenDaysLabel: '7 days',
    loadingHistory: 'Loading history...',
    noWorkoutFound: 'No workout found',
    tryOtherSearch: 'Try another search',
    newWorkoutBtn: 'New workout',
    weeklyProgress: 'Weekly progress',
    chargesByExercise: 'Weights by exercise',
    workoutsFoundCount: '{count} workout{plural} found',
    completedWorkoutsCount: '{count} completed workouts',
    avatarUploadError: 'Unable to upload avatar. Try again.',
    avatarDeleteTitle: 'Delete avatar',
    avatarDeleteConfirm: 'Do you really want to delete your profile photo?',
    avatarDeleteError: 'Unable to delete avatar.',
    profilePhoto: 'Profile photo',
    whatToDo: 'What do you want to do?',
    trackWorkoutNotFoundTitle: 'Workout not found',
    trackWorkoutNotFoundDesc: 'Go back to home to create or select a workout.',
    trackBackToHome: 'Back to home',
    trackExerciseMeta: '{count} exercise',
    trackExercisesMeta: '{count} exercises',
    trackSetMeta: '{count} set',
    trackSetsMeta: '{count} sets',
    trackSetsHeader: '{completed}/{total} sets',
    trackRest: 'Rest',
    trackNoExerciseTitle: 'No exercise',
    trackNoExerciseDesc: 'Add exercises from the creation screen to start tracking.',
    trackAddFirstSet: 'Add your first set',
    trackVideo: 'Video',
    trackSet: 'Set',
    trackRepeat: 'Repeat',
    trackValidate: 'Validate',
    trackLongPress: 'Long press',
    trackSetsValidated: 'sets validated',
    trackFinishWorkout: 'Finish workout',
    trackPendingSync: '{count} pending sync',
    trackOpenVideoError: 'Unable to open video',
    trackReps: 'Reps',
    trackWeight: 'Weight',
    trackRpe: 'RPE',
    welcomeGorillax: '🦍 Welcome to Gorillax!',
    configLater: 'You can set up your profile later in settings',
    accessApp: 'Access the app',

    // Exercise progression
    rangeLabelWeek: '7 days',
    rangeLabelMonth: '30 days',
    rangeLabelAll: 'All',
    progressionDash: 'Progression',
    progressChartDesc: 'Total load (weight × reps) on sessions containing this exercise.',
    progressMinSessions: 'Add at least three sessions with this exercise and weight data to display the progression chart.',
    noSessionForExercise: 'No sessions recorded for this exercise.',

    // CreateWorkoutScreen
    selectedExercises: 'Selected exercises',
    addExercisesFromCatalog: 'Add exercises from the catalog',
    searchExercisePlaceholder: 'Search exercise...',
    noExerciseFound: 'No exercise found',
    workoutReady: 'Workout ready!',
    exerciseCountAutoSave: '{count} exercise(s) • Auto save',

    // Objective units (for unit selector display)
    unitDays: 'days',

    // PersonalStats
    onlyXLeft: 'Only {count} left!',

    // DemoTourModal
    demoTourStepIndicator: 'Step {current}/{total}',
    demoTourSkip: 'Skip',
    demoTourAutoHint: 'Auto demo • ~30 s',
    demoTourStep1Title: 'Home',
    demoTourStep1Desc: 'Your dashboard: streak, weekly goal and next session.',
    demoTourStep2Title: 'Create a workout',
    demoTourStep2Desc: 'Give it a title, add exercises, log your sets (weight, reps) during training.',
    demoTourStep3Title: 'My Program',
    demoTourStep3Desc: 'Organize your weeks and start a session in one click from your program.',
    demoTourStep4Title: 'Network (Feed)',
    demoTourStep4Desc: 'See shared workouts, like, comment and browse profiles.',
    demoTourStep5Title: 'Explore & Challenges',
    demoTourStep5Desc: 'Join community challenges and compare yourself with others.',
    demoTourStep6Title: 'Messages',
    demoTourStep6Desc: 'Chat privately with other members from the Messages tab.',
    demoTourStep7Title: 'Profile & Settings',
    demoTourStep7Desc: 'Manage your profile, stats, settings and log out if needed.',
    demoTourStep8Title: 'Let\'s go!',
    demoTourStep8Desc: 'You know the basics. Have a great workout with Gorillax 🦍',

    // ErrorBoundary
    errorBoundaryTitle: 'Oops, something crashed',
    errorBoundaryMessage: 'An unexpected error occurred.',

    // ProgressCard
    totalSessions: 'Total sessions',
    kgLifted: 'Kg lifted',
    ofGoal: 'of goal',
    weeklyGoalReached: 'Weekly goal reached!',
    startFirstSession: 'Start your first session to see your stats here',
    sessionsOfGoal: '{current}/{goal} sessions',

    // Shared screen strings
    viewDetails: 'View details',
    plannedSets: 'Planned sets',
    createYourWorkout: 'Create your workout',
    workoutNameSection: 'Workout name',
    workoutNamePlaceholder: 'Ex: Push Day, Legs...',
    watchVideo: 'Watch video',
    notEnoughData: 'Not enough data',
    sessionHistory: 'Session history',

    // ExerciseChargesChart
    sessionCount: '{count} session(s)',

    // useAuth errors
    errorFetchProfile: 'Unable to fetch user profile',
    errorConnection: 'Connection error',
    errorWrongCredentials: 'Incorrect username or password',
    errorServerTimeout: 'The server is taking too long to respond. Try again in a few seconds (server waking up).',
    errorDemoConnection: 'Unable to connect to the demo account',
    errorServerTimeoutShort: 'The server is taking too long to respond. Try again in a few seconds.',
    errorRegistration: 'Registration error',
    errorRegistrationGeneric: 'An error occurred during registration',

    // CreateWorkoutScreen
    noWorkoutSelected: 'No workout selected',
    noWorkoutSelectedDesc: 'Create a new workout from the home screen to start training.',
    composeCustomWorkout: 'Compose your custom workout',
    catalogTitle: 'Catalog',
    variousMuscles: 'Various muscles',
    freeEquipment: 'Free equipment',
    noDescriptionYet: 'No description recorded yet.',
    detailedSheet: 'Detailed sheet',

    // HistoryScreen extra
    errorOccurred: 'An error occurred',
    stableLabel: 'Stable',
    syncLabel: 'Sync',

    // HistoryDetailScreen
    sessionNotFound: 'Workout not found',
    returnToHistoryDesc: 'Return to history to select a valid workout.',
    backToHistory: 'Back to history',
    duplicationFailed: 'Duplication failed',
    duplicationFailedDesc: 'We cannot duplicate this workout at the moment.',
    duplicationErrorDesc: 'An error occurred during duplication. Try again later.',
    connectToShareDesc: 'Log in to share your workout on the feed.',
    syncInProgress: 'Sync in progress',
    retryInFewSeconds: 'Try again in a few seconds.',
    repCount: '{count} rep(s)',

    // Premium / Paywall
    premiumActivated: 'Premium activated!',
    premiumActivatedDesc: 'You now have access to all features.',
    error: 'Error',
    purchaseError: 'Unable to complete the purchase.',
    restored: 'Purchase restored',
    restoredDesc: 'Your subscription has been successfully restored.',
    restoreError: 'Unable to restore. Check your App Store / Play Store account.',
    featureUnlimitedPrograms: 'Unlimited AI programs',
    featureAdvancedStats: 'Advanced stats & progression',
    featureFullHistory: 'Full workout history',
    featureUnlimitedObjectives: 'Unlimited custom objectives',
    featurePriority: 'Priority access to new features',
    paywallSubtitle: 'Unlock the full potential of Gorillax to reach your goals faster.',
    bestValue: 'Best value',
    yearlyPlan: 'Yearly',
    monthlyPlan: 'Monthly',
    perYear: '/year',
    perMonth: '/month',
    save33: '-33%',
    subscribe: 'Subscribe',
    restorePurchases: 'Restore purchases',
    subscriptionLegal: 'Subscription renews automatically. You can cancel anytime from your store settings.',
    premiumFeature: 'Premium Feature',
    upgradeToPremium: 'Upgrade to Premium',
    subscriptionLabel: 'Subscription',
    currentPlan: 'Current plan',
    freePlan: 'Free',
    premiumPlan: 'Premium',
    manageSubscription: 'Manage subscription',
    expiresOn: 'Expires on',
  },
};

// Hook pour utiliser les traductions
export const useTranslations = () => {
  const [isReady, setIsReady] = useState(false);
  const context = useContext(PreferencesContext);
  
  useEffect(() => {
    if (context && !context.isLoading) {
      setIsReady(true);
    }
  }, [context]);
  
  const t = (key: keyof typeof translations.fr | (string & {}), params?: Record<string, string | number>) => {
    // Si le contexte n'est pas prêt, retourner la clé
    if (!context || !isReady) {
      return key as string;
    }
    
    try {
      const { preferences } = context;
      let text = (translations[preferences.language] as Record<string, string>)?.[key as string] || key as string;
      
      // Remplacer les paramètres dans le texte (ex: {days} -> 3)
      if (params) {
        Object.entries(params).forEach(([param, value]) => {
          text = text.replace(`{${param}}`, String(value));
        });
      }
      
      return text;
    } catch (error) {
      console.warn('Translation error for key:', key, error);
      return key as string;
    }
  };
  
  const language = context?.preferences?.language ?? 'fr';

  return {
    t,
    language,
    isLoading: !isReady
  };
};