"""Add email verification and OAuth fields to User table

Revision ID: 20260122_170000
Revises: 20260122_162740
Create Date: 2026-01-22 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20260122_170000'
down_revision: Union[str, None] = '20260122_162740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to user table
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('email_verification_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('reset_password_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('reset_password_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('oauth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('oauth_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('login_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_count')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'oauth_id')
    op.drop_column('user', 'oauth_provider')
    op.drop_column('user', 'reset_password_expires')
    op.drop_column('user', 'reset_password_token')
    op.drop_column('user', 'email_verification_expires')
    op.drop_column('user', 'email_verification_token')
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###