"""Add login attempts table for rate limiting

Revision ID: 20260122_162740
Revises: d785ffa705c2
Create Date: 2026-01-22 16:27:40.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20260122_162740'
down_revision: Union[str, None] = 'd785ffa705c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loginattempt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loginattempt_ip_address'), 'loginattempt', ['ip_address'], unique=False)
    op.create_index(op.f('ix_loginattempt_username'), 'loginattempt', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loginattempt_username'), table_name='loginattempt')
    op.drop_index(op.f('ix_loginattempt_ip_address'), table_name='loginattempt')
    op.drop_table('loginattempt')
    # ### end Alembic commands ###