"""Add profile completion fields

Revision ID: 20260126_140000
Revises: 20260122_170000
Create Date: 2026-01-26 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '20260126_140000'
down_revision = '20260122_170000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('experience_level', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('training_frequency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('equipment_available', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_completed', sa.Boolean(), nullable=True, default=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('location')
        batch_op.drop_column('equipment_available')
        batch_op.drop_column('training_frequency')
        batch_op.drop_column('experience_level')

    # ### end Alembic commands ###