"""baseline

Revision ID: d785ffa705c2
Revises: 
Create Date: 2025-11-29 00:00:40.587674

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd785ffa705c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('muscle_group', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('equipment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    op.create_index(op.f('ix_exercise_slug'), 'exercise', ['slug'], unique=True)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_user_id'), 'program', ['user_id'], unique=False)
    op.create_table('syncevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consent_to_public_share', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_client_id'), 'workout', ['client_id'], unique=False)
    op.create_index(op.f('ix_workout_deleted_at'), 'workout', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workout_updated_at'), 'workout', ['updated_at'], unique=False)
    op.create_table('exercisealias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercisealias_name'), 'exercisealias', ['name'], unique=False)
    op.create_table('follower',
    sa.Column('follower_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('followed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('programsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('focus', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programsession_day_index'), 'programsession', ['day_index'], unique=False)
    op.create_table('share',
    sa.Column('share_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workout_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exercise_count', sa.Integer(), nullable=False),
    sa.Column('set_count', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('share_id')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('media_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_created_at'), 'story', ['created_at'], unique=False)
    op.create_index(op.f('ix_story_owner_id'), 'story', ['owner_id'], unique=False)
    op.create_table('workoutexercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('planned_sets', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workoutexercise_client_id'), 'workoutexercise', ['client_id'], unique=False)
    op.create_index(op.f('ix_workoutexercise_deleted_at'), 'workoutexercise', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workoutexercise_order_index'), 'workoutexercise', ['order_index'], unique=False)
    op.create_index(op.f('ix_workoutexercise_updated_at'), 'workoutexercise', ['updated_at'], unique=False)
    op.create_table('programset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_session_id', sa.Integer(), nullable=False),
    sa.Column('exercise_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reps', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['program_session_id'], ['programsession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programset_order_index'), 'programset', ['order_index'], unique=False)
    op.create_table('workoutset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workoutexercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workoutset_client_id'), 'workoutset', ['client_id'], unique=False)
    op.create_index(op.f('ix_workoutset_deleted_at'), 'workoutset', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workoutset_updated_at'), 'workoutset', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workoutset_updated_at'), table_name='workoutset')
    op.drop_index(op.f('ix_workoutset_deleted_at'), table_name='workoutset')
    op.drop_index(op.f('ix_workoutset_client_id'), table_name='workoutset')
    op.drop_table('workoutset')
    op.drop_index(op.f('ix_programset_order_index'), table_name='programset')
    op.drop_table('programset')
    op.drop_index(op.f('ix_workoutexercise_updated_at'), table_name='workoutexercise')
    op.drop_index(op.f('ix_workoutexercise_order_index'), table_name='workoutexercise')
    op.drop_index(op.f('ix_workoutexercise_deleted_at'), table_name='workoutexercise')
    op.drop_index(op.f('ix_workoutexercise_client_id'), table_name='workoutexercise')
    op.drop_table('workoutexercise')
    op.drop_index(op.f('ix_story_owner_id'), table_name='story')
    op.drop_index(op.f('ix_story_created_at'), table_name='story')
    op.drop_table('story')
    op.drop_table('share')
    op.drop_index(op.f('ix_programsession_day_index'), table_name='programsession')
    op.drop_table('programsession')
    op.drop_table('follower')
    op.drop_index(op.f('ix_exercisealias_name'), table_name='exercisealias')
    op.drop_table('exercisealias')
    op.drop_index(op.f('ix_workout_updated_at'), table_name='workout')
    op.drop_index(op.f('ix_workout_deleted_at'), table_name='workout')
    op.drop_index(op.f('ix_workout_client_id'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('syncevent')
    op.drop_index(op.f('ix_program_user_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_exercise_slug'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
