services:
  - type: web
    name: gorillax-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: cd src && uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: EXERCISES_URL
        value: "https://drive.google.com/file/d/1tK7OdUg96GSYgNPO08bukqb-gZOmxpHY/view?usp=sharing"


